angular.module('employeeScope', [])
.controller('EmployeeController', ['$scope', function ($scope) {


    $scope.getEmployeeList = function () {
        return $.ajax({
            type: "GET",
            url: "/api/api_Employee",
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            async: false,
            success: function (html) {
                return html;
            }
        }).responseText;
    };
    $scope.employeeList = JSON.parse($scope.getEmployeeList());


    $scope.mock = [
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },
            {
                EmployeeID: 'xz111',
                FirstName: 'Adam',
                LastName: 'Ostrowski',
                Title: 'Master',
                TitleOfCurtesy: 'Sir',
                BirthDate: "10/10/90",
                HireDate: "22/05/14",
                Address: 'Prosta 16',
                City: 'Kraków',
                Region: 'Akademiki',
                PostalCode: '85-951',
                Country: 'Polska',
                HomePhone: '12 235 45 63',
                Extension: '-',
                Photo: '-',
                Notes: '-',
                ReportsTo: 'Admin',
                PhotoPath: '-',
            },



    ]

    $scope.checkQuery2 = function () {
        if ($scope.query2.length == 0) {
            $scope.query2 = undefined;
        }

    };


}]);

